[project]
name = "aoc"
version = "1.0.0"
authors = [{ name = "Zak Johnson", email = "me@zakj.net" }]
dependencies = [
    "websockets>=12.0",
]
requires-python = ">=3.12,<3.13"
license = { text = "MIT" }

[tool.uv]
package = true
